apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managed-services
  template:
    metadata:
      labels:
        app: managed-services
    spec:
      terminationGracePeriodSeconds: 5
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
      - name: service-server
        image: us-central1-docker.pkg.dev/xg-ai-controller-77/xg-ai-images/serviceservice:v1-amd64
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "9192"
        - name: PATHCOMPSERVICE_SERVICE_HOST
          value: "127.0.0.1"
        - name: PATHCOMPSERVICE_SERVICE_PORT_GRPC
          value: "10020"
        envFrom:
        - secretRef:
            name: crdb-data
        - secretRef:
            name: nats-data
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: pathcomp-frontend
        image: us-central1-docker.pkg.dev/xg-ai-controller-77/xg-ai-images/pathcomp-frontend:v1-amd64
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENABLE_FORECASTER
          value: "NO"
        - name: METRICS_PORT
          value: "9193"
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: pathcomp-backend
        image: us-central1-docker.pkg.dev/xg-ai-controller-77/xg-ai-images/pathcomp-backend:v1-amd64
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: slice-server
        image: us-central1-docker.pkg.dev/xg-ai-controller-77/xg-ai-images/sliceservice:v1-amd64
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "9194"
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: optical-server
        image: labs.etsi.org:5050/tfs/controller/opticalcontroller:latest
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "9195"
        - name: CRDB_DATABASE
          value: "tfs_optical"
        envFrom:
        - secretRef:
            name: crdb-data
        - secretRef:
            name: nats-data
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: qkd-server
        image: labs.etsi.org:5050/tfs/controller/qkd_app:latest
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "9196"
        - name: CRDB_DATABASE
          value: "tfs_qkd"
        envFrom:
        - secretRef:
            name: crdb-data
        - secretRef:
            name: nats-data
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
