
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-public
  labels:
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/component: database
spec:
  ports:
  - port: 26257
    targetPort: 26257
    name: sql
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/component: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  serviceName: cockroachdb-public
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb
      app.kubernetes.io/instance: cockroachdb
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cockroachdb
        app.kubernetes.io/instance: cockroachdb
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:latest-v22.2
        args:
        - start-single-node
        - --insecure
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 26257
          name: sql
        env:
        - name: COCKROACH_DATABASE
          value: tfs_context
        - name: COCKROACH_USER
          value: tfs
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
